device: cuda:0
note: "knn_gravnet_3k"
seed: 42
log_tensorboard: false
num_threads: 5


model_name: gnn_gravnet
model_kwargs:
  hidden_dim: 72
  out_dim: 12
  num_layers: 4
  k: 32
  knn_dim: 32


loss_name: knninfonce
loss_kwargs:
  dist_metric: l2_rbf
  tau: 0.05


optimizer_name: adam
num_epochs: 2000
batch_size: 1
optimizer_kwargs:
  lr: 2.0e-4


lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 500


data_dir: ../data/
dataset_name: tracking-3k
main_metric: accuracy@0.9
mode: max
