device: cuda:0
seed: 42
log_tensorboard: false
num_threads: 1
note: "fullhybrid2_15k_record"

model_name: fullhybrid2_fullhybrid2
model_kwargs:
  out_dim: 12
  n_layers: 3
  drop_out: 0.1
  drop_out_in_block: 0.0
  drop_path: 0.0
  h_dim: 128
  n_hashes: 3
  num_group: 243
  num_heads: 8
  num_regions: 100
  num_w_per_dist: 10
  mlp_layers: 4
  block_size: 100 
  pe_type: none
  num_w_per_dist: 10



loss_name: knninfonce
loss_kwargs:
  dist_metric: l2_rbf
  tau: 0.05


optimizer_name: adam
num_epochs: 1000
batch_size: 1
optimizer_kwargs:
  lr: 1.0e-3


#lr_scheduler_name: impatient
#lr_scheduler_metric: loss
#lr_scheduler_kwargs:
#  mode: min
#  factor: 0.5         
#  patience: 3        
#  verbose: true      
lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 75


data_dir: ../data/
dataset_name: tracking-15k
main_metric: accuracy@0.9
mode: max
