device: cuda:0
seed: 42
log_tensorboard: false
num_threads: 5
note: "knn_hydra_15k"
# num_regions 140 if 6k 150 if tracking-60k

model_name: hydra_hydra
model_kwargs:
  out_dim: 12
  drop_out: 0.1
  drop_out_in_block: 0.0
  drop_path: 0.0
  encoder_dim: 48
  group_size: 24
  h_dim: 48
  n_hashes: 3
  n_layers: 8
  num_group: 243
  num_heads: 8
  num_regions: 120
  num_w_per_dist: 10
  block_size: 100
  pe_type: none
  rms_norm: false
  trans_dim: 96
  mlp_layers: 4
  num_slices_per_axis: 30
  group_size: 200
  pe_type: learned
  B: 1000


loss_name: knninfonce
loss_kwargs:
  dist_metric: l2_rbf
  tau: 0.05


optimizer_name: adam
num_epochs: 2000
batch_size: 1
optimizer_kwargs:
  lr: 1.0e-4


lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 500


data_dir: ../data/
dataset_name: tracking-15k
main_metric: accuracy@0.9
mode: max
