device: cuda:0
note: "casualformer_3k_record"
seed: 42
log_tensorboard: false
num_threads: 5


model_name: trans_casualformer
model_kwargs:
  pe_type: none
  num_heads: 4
  h_dim: 24
  n_layers: 2
  num_w_per_dist: 10


loss_name: knninfonce
loss_kwargs:
  dist_metric: l2_rbf
  tau: 0.05


optimizer_name: adam
num_epochs: 1000
batch_size: 1
optimizer_kwargs:
  lr: 2.0e-4


lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 500


data_dir: ../data/
dataset_name: tracking-3k
main_metric: accuracy@0.9
mode: max
